@port = 3002

### List Events
GET http://localhost:{{port}}/api/v1/event/list

### Create Event
POST http://localhost:{{port}}/api/v1/event
Content-Type: application/json

{
    "name": "Jake's secret party",
    "dates": [
        "2014-01-01",
        "2014-01-05",
        "2014-01-12"
    ]
}

### Show Event
GET http://localhost:{{port}}/api/v1/event/1

### Vote Event
POST http://localhost:{{port}}/api/v1/event/1/vote
Content-Type: application/json

{
    "name": "Dick",
    "votes": [
        "2014-01-01",
        "2014-01-05"
    ]
}

### Show Voting Results
GET http://localhost:{{port}}/api/v1/event/1/results